language: php
php:
- 7.0
branches:
  only:
  - feature/7-package
  - master
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 2.0
  - 3.0
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_install:
- chmod +x $TRAVIS_BUILD_DIR/scripts/travis/before_install.sh
- $TRAVIS_BUILD_DIR/scripts/travis/before_install.sh
script:
- chmod +x $TRAVIS_BUILD_DIR/scripts/travis/build.sh
- $TRAVIS_BUILD_DIR/scripts/travis/build.sh
env:
  global:
  - secure: ECROWx4vJF3jLwt5A+Nf2kIgHvU7CiwekbBWGN/EXJZM+7fXH188RyTA5Tuf1ipT2qb7N8HGZz+Fe936FNvukw46UAksTC4WbzY7oyFR29EN11+ePes6kij0ypXZlhFa2HGRtn3dBfHBxtMqnDaJ8GlKKGMRQSM7vF6UyzPPYYDklKLdCeWqEdZiQtj8twshyiVimV0qAvnWMygIzsbmEJtNdYK7ifRqASDybnh1fWDZRti+gz7L2p2Z4CFLLugV9v3hCjg2AMX1xdTuP/937SNu+gWWfcl7U1tyisCfMFfaX/7agKix+1cPscENInE+ekld70T7zVJ+C0nqf+RpB75NrbjkH5Ot1kk4Hw6UCr1wNJppIUpuzmykEwZOHNiWw/txShe8+KceWDeUfYMcCSjnjv1d2ZIBDr7GTfOHqTfwOdGP9HjnexKx43qK87nq109uOpjOhFMBO/XyHc9fFY+T1DKHCFclh7E1ai8+8+s7vOkcRoqxYxB8aMUNEAPT8VCjtuISX1lxUHtxZ9bCAbyQhnpzWe2+geIyuGCRhBGhNyF93jLWUjpLxy0x/ZxlsE3co84zVifzXqfVWX8dJ73CPg+ObT+wmzQGh4yNoZJt4qj+Z7inkCQRswKOut3gCsn0m129QeCOvcK2SYpkFtIYSsBD49IbXi4UHix58Ew=
